apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: microk8s
  environments:
  - key: dev
    owner: mr-coveros
    repository: jx3-microk8s
  - key: staging
  - key: production
  ingress:
    domain: jenkinsx.cluster.local
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: mr-coveros
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
